spring:
    application:
        name: ${APP_NAME:checkout-lab}
    datasource:
        url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB_NAME}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
    level:
        web: ${LOG_LEVEL:INFO}
